# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweethearts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pubDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(),
        ),
    ]
