# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweethearts', '0002_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(max_length=40, verbose_name='摘要'),
        ),
    ]
