# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweethearts', '0002_auto_20180621_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '我 们 的 足 迹'},
        ),
    ]
