# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweethearts', '0003_auto_20180625_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guestbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mssge', models.TextField(verbose_name='留言')),
                ('name', models.CharField(default='', max_length=20, verbose_name='访客')),
                ('gbtime', models.DateTimeField(auto_now=True, verbose_name='留言时间')),
            ],
        ),
    ]
